name: build-qemu

on:
  push:
    branches:
      - main
    tags:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: |
          ./build.sh
      - name: Upload mdbook artifacts
        uses: actions/upload-artifact@v4
        with:
          name: qemu-9.2.3-ubuntu-24.04.tar.gz
          path: qemu-9.2.3-ubuntu-24.04.tar.gz
          if-no-files-found: error
      - name: Create and Upload Release
        if: github.event_name == 'push' && startswith(github.ref, 'refs/tags/')
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          artifacts: qemu-9.2.3-ubuntu-24.04.tar.gz
          allowUpdates: true
          updateOnlyUnreleased: true
